### ISSUE TITLE
(Ghost ) -  reference to Sentence Node for each test (ghost ...)

### ISSUE THREAD

**Issue by simonmekit** [singnet/opencog-tutorials#12]
I'm running Ghost code-base alone with ECAN. After updating to latest singularitynet repos (cogutil, atomspace and opencog), the (ghost ...) command resulted in a reference response for any kind of input. 
    guile> (ghost-parse "#goal: (novelty=0.24) u: (eat apple) I eat apple too ^keep")
       guile> (ghost "eat apple")
          (SentenceNode "sentence@1c54890c-f2ef-4ea9-9f86-d3621f8793c7")
       guile> (ghost "eat apple")
           (SentenceNode "sentence@08258d84-31f3-477f-a296-9eb7ee43b8ed")
   guile> (ghost-parse "u: (hi robot) Hello human!")
        guile> (ghost "hi robot")
            (SentenceNode "sentence@ab6bd8de-7495-4e93-b9a6-2212012116a0")

**Comment by smigad** [comment]
use `(ghost-get-result)` after (ghost TXT)

**Comment by simonmekit** [comment]
thanks @Dagiopia,
that doesn't work. ecan-based-ghost-rules  is set to true, so i'm using (ghost " ...") command

**Comment by smigad** [comment]
the function `(ghost TXT)` use to run blocking mode until a result is obtained (a result may suddenly appear when the relevant topic enters the attentional focus).
https://github.com/opencog/opencog/commit/8e5e69eb086b964f2f0a4e5ce3e627ce8a2d17ca 
this changed that.
